[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "uapi"
version = "0.2.dev0"
description = "A Python HTTP superframework"
authors = [{name = "Tin Tvrtkovic", email = "tinchester@gmail.com"}]
classifiers = ["License :: OSI Approved :: Apache Software License"]
dependencies = ["cattrs >= 22.1.0", "incant >= 0.3", "itsdangerous"]
requires-python = ">=3.9"

[project.optional-dependencies]
dev = [
    "black",
    "flake8",
    "isort",
    "coverage",
    "pytest-asyncio",
    "httpx",
    "aiohttp",
    "flask",
    "quart",
    "starlette",
    "hypercorn",
    "mypy",
    "aioredis",
    "uvicorn",
    "orjson",
]

[tool.isort]
profile = "black"

[tool.pytest.ini_options]
asyncio_mode = "auto"

[tool.black]
skip_magic_trailing_comma = true

[tool.mypy]
warn_unused_ignores = true