[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "attrsapi"
version = "0.1"
description = ""
authors = [{name = "Tin Tvrtkovic", email = "tinchester@gmail.com"}]
classifiers = ["License :: OSI Approved :: Apache Software License"]
dependencies = ["cattrs"]
requires-python = ">=3.9"

[project.optional-dependencies]
dev = [
    "black",
    "flake8",
    "pytest-asyncio",
    "httpx",
    "aiohttp",
    "flask",
    "quart",
    "starlette",
    "hypercorn",
]

[tool.isort]
profile = "black"
